spring:
  datasource:
    url: jdbc:mysql://192.168.142.135:3306/composerdb
    username: composer
    password: composerJA;VA2
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
  quartz:
    job-store-type: memory