spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./data/core_data
    username: composer
    password: composerJAVA
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  #    show_sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  quartz:
    job-store-type: memory