script_groups:
  - group_name: SN1
    job_type: one
    commands:
      - command_arg_seq:
          - python38
          - sycm_compose.py
          - -c xx
          - -n nn
      - command_arg_seq:
          - python38
          - sycm_compose.py
          - -c yy
          - -n nn
    working_dir: /home/mgmt/Daily
    start_at: xxx

  - group_name: SN2
    job_type: cron
    commands:
      - command_arg_seq:
          - python38
          - jdsz_compose.py
          - -c xxx
          - -n nn
      - command_arg_seq:
          - python38
          - jdsz_compose.py
          - -c yyy
          - -n nn
    working_dir: /home/mgmt/Daily
    start_at: xxx