script_groups:
  - group_name: SN1_1
    cluster: SN1
    job_type: one
    # seconds
    interval: 10
    commands:
      - command_arg_seq:
          - python
          - -u
          - sycm_compose.py
          - -c 1.txt
      - command_arg_seq:
          - python
          - -u
          - sycm_compose.py
          - -c sb.txt
    working_dir: C:\Users\ckhoi\IdeaProjects\ScriptsCompose
    start_at: '2021-11-21 15:45:00'

  - group_name: SN1_2
    cluster: SN1
    job_type: cron
    # seconds
    interval: 0
    commands:
      - command_arg_seq:
          - python
          - -u
          - sycm_compose.py
          - -c nmsl.txt
#      - command_arg_seq:
#          - python38
#          - jdsz_compose.py
#          - -c yyy
#          - -n nn
    working_dir: C:\Users\ckhoi\IdeaProjects\ScriptsCompose\
    start_at: '0 * * ? * * *'